name: Build Debian Package

on:
  push:
    branches: [branchAutoPackage, master]
  pull_request:
    branches: [branchAutoPackage, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from branchAutoPackage
      uses: actions/checkout@v4
      with:
        ref: branchAutoPackage

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool build-essential devscripts debhelper curl

    - name: Download release tarball
      run: |
        curl -LJO https://github.com/cheryxso/DevOps/releases/download/v.1/myprogram-1.0.tar.gz

    - name: Check if tarball is valid gzip
      run: |
        file myprogram_1.0.orig.tar.gz
        if [[ $(file -b myprogram_1.0.orig.tar.gz) != *"gzip compressed data"* ]]; then
          echo "Error: File is not a valid gzip archive.";
          exit 1;
        fi

    - name: Unpack tarball
      run: |
        tar xzf myprogram_1.0.orig.tar.gz

    - name: Create debian files
      run: |
        mkdir -p debian
        echo "Source: myprogram" > debian/control
        echo "Version: 1.0-1" >> debian/control
        echo "Section: misc" >> debian/control
        echo "Priority: optional" >> debian/control
        echo "Architecture: any" >> debian/control
        echo "Maintainer: Ksenia <cheryxso@gmail.com>" >> debian/control
        echo "Description: My program for creating Debian packages" >> debian/control
        echo "myprogram (1.0-1) unstable; urgency=low" > debian/changelog
        echo "  * Initial release." >> debian/changelog
        echo "" >> debian/changelog
        echo " -- Ksenia <cheryxso@gmail.com>  $(date -R)" >> debian/changelog
        echo "9" > debian/compat
        echo "#!/usr/bin/make -f" > debian/rules
        echo "%:" >> debian/rules
        echo "\tdh $@" >> debian/rules
        chmod +x debian/rules

    - name: Build the project
      run: make

    - name: Create Debian package
      run: debuild -us -uc

    - name: Upload Debian Package
      uses: actions/upload-artifact@v4
      with:
        name: myprogram-deb-package
        path: ../*.deb
