name: Build Debian Package

on:
  push:
    branches: [branchAutomake, branchAutoPackage, master]
  pull_request:
    branches: [branchAutomake, branchAutoPackage, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from branchAutoPackage
      uses: actions/checkout@v4
      with:
        ref: branchAutoPackage
        
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential devscripts debhelper fakeroot lintian
        
    - name: Generate configure script
      run: autoreconf -i

    - name: Configure the project
      run: ./configure

    - name: Checkout code from branchAutomake for artifact download
      uses: actions/checkout@v4
      with:
        ref: branchAutomake  

    - name: List uploaded artifacts
      run: |
        ls -l /github/workspace/  

    - name: Download tarball from artifacts
      uses: actions/download-artifact@v4
      with:
        name: myprogram-tarball
        path: ./

    - name: Unpack tarball
      run: |
        tar xzf myprogram_1.0.orig.tar.gz

    - name: Create debian files
      run: |
        mkdir -p debian
        echo "Source: myprogram" > debian/control
        echo "Version: 1.0-1" >> debian/control
        echo "Section: misc" >> debian/control
        echo "Priority: optional" >> debian/control
        echo "Architecture: any" >> debian/control
        echo "Maintainer: Ksenia <cheryxso@gmail.com>" >> debian/control
        echo "Description: My program for creating Debian packages" >> debian/control
        echo "myprogram (1.0-1) unstable; urgency=low" > debian/changelog
        echo "  * Initial release." >> debian/changelog
        echo "" >> debian/changelog
        echo " -- Ksenia <cheryxso@gmail.com>  $(date -R)" >> debian/changelog
        echo "9" > debian/compat
        echo "#!/usr/bin/make -f" > debian/rules
        echo "%:" >> debian/rules
        echo "\tdh $@" >> debian/rules
        chmod +x debian/rules
        
    - name: Build the project
      run: make

    - name: Create Debian package
      run: debuild -us -uc

    - name: Upload Debian package as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: myprogram-debian-package
        path: ../*.deb
