name: Build and Link Binary

on:
  push:
    branches:
      - branchMake
  pull_request:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Checkout branchMake
      run: git checkout branchMake

    - name: Set up build environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y build-essential

    - name: Build the project with Makefile
      run: |
        make clean
        make

    - name: Verify if the binary exists
      run: |
        if [ ! -f ./program ]; then
          echo "Error: Binary file was not created!" && exit 1
        else
          echo "Success: Binary file is created."
        fi
