name: CI for Unit Tests

on:
  push:
    branches: 
      - branchAutoTest
      - master
  pull_request:
    branches: 
      - branchAutoTest
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify configure.ac exists
        run: |
          if [ ! -f configure.ac ]; then
            echo "Error: configure.ac is missing."
            exit 1
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config cmake

      - name: Generate configure script
        run: autoreconf -i

      - name: Configure the project
        run: ./configure

      - name: Build the project
        run: make

      - name: Run unit tests
        run: make check
