name: CI for Unit Tests

on:
  push:
    branches: [branchAutoTest, master]
  pull_request:
    branches: [branchAutoTest, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build the project
      run: |
        g++ -o my_program main.cpp FuncA.cpp -lgtest -lgtest_main -pthread
        g++ -o test_program test_func_a.cpp FuncA.cpp -lgtest -lgtest_main -pthread

    - name: Run unit tests
      run: ./test_program
